services:
  db:
    image: postgres:alpine
    container_name: easybuy-db
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: easybuy-redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: easybuy-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  server:
    build: ./server
    container_name: easybuy-server
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - ./server/.env
    environment:
      DATABASE_HOST: db
      REDIS_ADDRESS: redis:6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/

  client:
    build:
      context: ./client
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    container_name: easybuy-client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server
    env_file:
      - ./client/.env

volumes:
  postgres_data: